robot_name: "LINGYU_ROBOT"
dof: 7
manufacturer: "Lingyu"

isaac_sim:
  usd_path: "assets/usd/lingyu_robot.usd"  # To be converted from URDF
  urdf_path: "robots/lingyu_robot/urdf/urdf20251126.urdf"
  ee_frame: "end_effector"
  prim_path: "/World/LingyuRobot"

real_robot:
  backend_type: "lingyu_sdk"
  connection:
    ip: "192.168.1.101"

workspace_limits:
  x: [-0.8, 0.8]
  y: [-0.8, 0.8]
  z: [0.0, 1.2]

controller:
  max_velocity: 0.4
